#!/usr/bin/env sh

CMD=$1

if [ "$CMD" = "run" ]; then
  source .env

  ./src/generate_ssh_key.sh

  LOCAL_WORKSPACE=${PWD}/workspace

  REPOSITORY_URL=$REPOSITORY_URL \
    LOCAL_WORKSPACE=$LOCAL_WORKSPACE \
    BRANCH=$BRANCH \
    ./src/checkout_project.sh

  LOCAL_WORKSPACE=$LOCAL_WORKSPACE \
    BRANCH=$BRANCH \
    IMAGE=$IMAGE \
    ./src/trigger_build.sh
fi
